[build-system]
requires = ["poetry-core>2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "GRLP-Network-Response-Periodic-Forcing"
version = "2.1"
authors = [
  {name = "Fergus McNab", email = "fergus.mcnab@gfz.de"}
]
description = "Analyse response of GRLP networks to periodic variation in sediment and water supply, for the paper McNab et al. (2025, ESurf)."
readme = "README.md"
requires-python = ">3.9"
dependencies = [
  "grlp @ git+https://github.com/MNiMORPH/GRLP.git@v2.0.0",
  "numpy (==2.0.2)",
  "scipy (==1.13.1)"
]

[tool.poetry]
packages = [{include = "grlp_extras.py", from = "src"}]